# Generated by Django 3.2.6 on 2021-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210813_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypes',
            name='brief',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
